const $=s=>document.querySelector(s);let token=null,busy=false;
const labels={budgetFiles:'แฟ้มงาน',networks:'โครงข่าย',accounts:'รหัสบัญชี',costCenters:'ศูนย์ต้นทุน',people:'บุคลากร'};
const types={budgets:'Data ของงบแฟ้มงาน',accounts:'รหัสบัญชี',people:'รายชื่อบุคลากร'};
function setBusy(value){busy=value;for(const id of ['check-import','import-kind','import-file','confirm-import'])$('#'+id).disabled=value;}
function invalidatePreview(){token=null;$('#import-preview').hidden=true;$('#admin-status').textContent='';}
$('#import-kind').onchange=invalidatePreview;$('#import-file').onchange=invalidatePreview;
async function refresh(){const r=await fetch('/master-data.json');if(!r.ok)throw Error('อ่านข้อมูลปัจจุบันไม่ได้');const data=await r.json();$('#admin-current').textContent=`ปัจจุบัน: ${data.budgetFiles.length} แฟ้มงาน · ${data.budgetFiles.reduce((a,f)=>a+f.networks.length,0)} โครงข่าย · ${data.accounts.length} รหัสบัญชี · ${data.costCenters.length} ศูนย์ต้นทุน · ${data.people.length} คน`;$('#admin-history').replaceChildren();for(const [kind,label]of Object.entries(types)){const li=document.createElement('li'),u=data.updates?.[kind];li.textContent=label+': '+(u?u.filename+' — '+new Date(u.updatedAt).toLocaleString('th-TH'):'ข้อมูลตั้งต้น ยังไม่มีการอัปเดตผ่านหน้านี้');$('#admin-history').append(li);}}
$('#import-form').onsubmit=async e=>{e.preventDefault();if(busy)return;invalidatePreview();const file=$('#import-file').files[0];if(!file)return;if(!file.name.toLowerCase().endsWith('.xlsx')||file.size>15*1024*1024){$('#admin-status').textContent='กรุณาเลือกไฟล์ .xlsx ขนาดไม่เกิน 15 MB';return;}setBusy(true);$('#admin-status').textContent='กำลังตรวจไฟล์…';try{const r=await fetch('/api/admin/preview/'+$('#import-kind').value,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const result=await r.json();if(!r.ok)throw Error(result.error);token=result.token;$('#import-filename').textContent=result.filename;$('#import-counts').replaceChildren();for(const [key,label]of Object.entries(labels)){const tr=document.createElement('tr');for(const text of [label,result.before[key],result.after[key]]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('#import-counts').append(tr);}$('#import-warnings').textContent=result.warnings.join(' · ');$('#import-sample').replaceChildren();for(const row of result.sample){const li=document.createElement('li');li.textContent=[row.code,row.name,row.position,row.networks?row.networks.length+' โครงข่าย':''].filter(Boolean).join(' — ');$('#import-sample').append(li);}$('#import-preview').hidden=false;$('#admin-status').textContent='ตรวจไฟล์ผ่านแล้ว กรุณาตรวจจำนวนข้อมูลก่อนยืนยัน';}catch(err){$('#admin-status').textContent=err.message;}finally{setBusy(false);}};
$('#confirm-import').onclick=async()=>{if(busy||!token)return;setBusy(true);try{const r=await fetch('/api/admin/commit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const result=await r.json();if(!r.ok)throw Error(result.error);token=null;$('#import-preview').hidden=true;$('#admin-status').textContent='อัปเดตสำเร็จ และสำรองข้อมูลเดิมไว้แล้ว';try{await refresh();}catch(e){$('#admin-status').textContent+=' · โหลดจำนวนล่าสุดไม่สำเร็จ กรุณาโหลดหน้าใหม่';}}catch(err){$('#admin-status').textContent=err.message;}finally{setBusy(false);}};
refresh().catch(e=>$('#admin-current').textContent=e.message);

fetch('/api/admin/budget-sources').then(r=>r.json()).then(data=>{for(const key of ['I','C'])document.querySelector('#source-form').elements[key].value=data[key];}).catch(()=>{$('#source-status').textContent='อ่านลิงก์ไม่สำเร็จ กรุณาโหลดหน้าใหม่';});
$('#source-form').onsubmit=async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button');button.disabled=true;try{const r=await fetch('/api/admin/budget-sources',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({I:form.elements.I.value,C:form.elements.C.value})});const result=await r.json();if(!r.ok)throw Error(result.error);$('#source-status').textContent='บันทึกลิงก์แล้ว ผู้ใช้ต้องกดดึงข้อมูลใหม่ก่อนสร้างเอกสาร';}catch(error){$('#source-status').textContent=error.message;}finally{button.disabled=false;}};
