const $=s=>document.querySelector(s),form=$('#form');
const initial={department:'ผปร.',description:'วัสดุและอุปกรณ์สำหรับงานช่าง จำนวน 3 รายการ',reason:'เพื่อทดแทนวัสดุเดิมที่ชำรุด',vendor:'ร้านค้าตัวอย่าง (ข้อมูลสมมติ)',days:3,costCenter:'A311201010',budgetFile:'I-69-A-PHOPS.JL.0005',network:'7001169470',expense:'ค่าเบ็ดเตล็ด (0060)',account:'53051090 (ค่าวัสดุเบ็ดเตล็ดด้านช่าง)',chair:'ประธานตัวอย่าง',member1:'กรรมการตัวอย่างหนึ่ง',member2:'กรรมการตัวอย่างสอง',officer:'เจ้าหน้าที่ตัวอย่าง',approver:'ผู้อนุมัติตัวอย่าง',receiver:'ผู้รับของตัวอย่าง'};
let draftReady=false,draftDirty=false,draftSaving=false,draftTimer=null;
let photos=[],photoBusy=false,photoGeneration=0;
let budgets=[],items=[],proposal=null,url=null,version=0,busy=false;const money=n=>(n/100).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});const cents=v=>Math.round((Number(v)||0)*100);const base=r=>Math.round(Number(r.qty)*cents(r.price));
function invalidate(){scheduleDraft();version++;proposal=null;$('#allocation').hidden=true;if(url){URL.revokeObjectURL(url);url=null}$('#pdf').hidden=true;$('#download').hidden=true;$('#document-print').hidden=true;$('#empty').hidden=false;$('#preview-status').textContent='ข้อมูลเปลี่ยนแล้ว';}
function totals(){let s=items.reduce((a,r)=>a+base(r),0),v=items.reduce((a,r)=>a+cents(r.vat),0);$('#count').textContent=items.length+' รายการ';$('#subtotal').textContent=money(s);$('#vat').textContent=money(v);$('#grand').textContent=money(s+v);$('#totalvat').value=(v/100).toFixed(2);$('#limit').textContent=s+v>1000000?'ยอดเกินขอบเขต 10,000 บาท':'อยู่ในขอบเขตไม่เกิน 10,000 บาท';$('#limit').classList.toggle('bad',s+v>1000000);$('#preview').disabled=busy||s+v>1000000;$('#add').disabled=false;$('#docno').value=`น.1กฟส.พร้าว(${{'ผปร.':'ปร.','ผบค.':'บค.','ผบง.':'บง.'}[form.elements.department.value]}) ___ / ${new Date().getFullYear()+543}`;document.querySelectorAll('.rowtotal').forEach((el,i)=>el.textContent=money(base(items[i])+cents(items[i].vat)));if(budgets.length)updateBudgetStatus();}
function render(){const body=$('#rows');body.replaceChildren();items.forEach((row,i)=>{const tr=document.createElement('tr');for(const key of ['name','qty','price','vat']){const td=document.createElement('td'),input=document.createElement('input');input.value=row[key];input.setAttribute('aria-label',`${key} รายการ ${i+1}`);input.required=true;if(key==='name')input.maxLength=45;else {input.type='number';input.min=key==='qty'?'0.01':'0';input.step='0.01'}input.oninput=()=>{row[key]=input.value;if(key==='vat')row.manual=true;if((key==='qty'||key==='price')&&!row.manual){row.vat=(Math.round(base(row)*.07)/100).toFixed(2);tr.children[3].querySelector('input').value=row.vat}invalidate();totals();};td.append(input);if(key==='vat'){const b=document.createElement('button');b.type='button';b.className='quiet';b.textContent=row.manual?'กำหนดเอง · คืนอัตโนมัติ':'อัตโนมัติ 7%';b.onclick=()=>{row.manual=false;row.vat=(Math.round(base(row)*.07)/100).toFixed(2);invalidate();render();};td.append(b)}tr.append(td)}const t=document.createElement('td');t.innerHTML='<span class="rowtotal"></span>';tr.append(t);const last=document.createElement('td'),remove=document.createElement('button');remove.type='button';remove.className='remove';remove.textContent='×';remove.setAttribute('aria-label','ลบรายการ '+(i+1));remove.disabled=items.length===1;remove.onclick=()=>{items.splice(i,1);budgets.forEach(b=>b.itemIndices=b.itemIndices.filter(j=>j!==i).map(j=>j>i?j-1:j));invalidate();render();renderBudgets()};last.append(remove);tr.append(last);body.append(tr)});totals()}
function reset(){photoGeneration++;photos=[];renderPhotos();for(const [k,v]of Object.entries(initial))form.elements[k]&&(form.elements[k].value=v);items=[{name:'แบตเตอรี่สำหรับเครื่องมือช่าง',qty:2,price:1000,vat:139.99,manual:true},{name:'ถุงมือสำหรับงานช่าง',qty:3,price:300,vat:63,manual:false},{name:'เทปพันสายไฟ',qty:4,price:150,vat:42.02,manual:false}];budgets=[{type:'งบแฟ้มงาน',costCenter:initial.costCenter,budgetFile:initial.budgetFile,network:initial.network,expense:initial.expense,account:initial.account,itemIndices:[0,1,2]}];$('#member-count').value='2';setMembers();invalidate();render();renderBudgets();$('#message').textContent='';}
form.addEventListener('input',e=>{if(e.target.name){invalidate();totals()}});form.onsubmit=e=>e.preventDefault();$('#reset').onclick=()=>{if(confirm('แทนที่ร่างปัจจุบันด้วยข้อมูลตัวอย่าง? กรุณาดาวน์โหลด PDF ที่ต้องการเก็บก่อน'))reset();};$('#add').onclick=()=>{if(true){items.push({name:'',qty:1,price:0,vat:0,manual:false});invalidate();render();renderBudgets()}};
$('#autovat').onclick=()=>{items.forEach(r=>{r.manual=false;r.vat=(Math.round(base(r)*.07)/100).toFixed(2)});invalidate();render()};
$('#allocate').onclick=()=>{const target=cents($('#totalvat').value),locked=items.reduce((a,r)=>a+(r.manual?cents(r.vat):0),0),free=items.map((r,i)=>r.manual?-1:i).filter(i=>i>=0),left=target-locked,den=free.reduce((a,i)=>a+base(items[i]),0);if(target<0||left<0||(!free.length&&left)||(!den&&left)){ $('#message').textContent='ยอดรวมขัดกับ VAT ที่กำหนดเอง กรุณาคืนแถวที่ต้องการปรับเป็นอัตโนมัติก่อน';return}proposal=items.map(r=>cents(r.vat));const shares=free.map(i=>({i,value:den?left*base(items[i])/den:0}));shares.forEach(x=>proposal[x.i]=Math.floor(x.value));let remainder=left-shares.reduce((a,x)=>a+Math.floor(x.value),0);shares.sort((a,b)=>(b.value%1)-(a.value%1)||a.i-b.i);for(let j=0;j<remainder;j++)proposal[shares[j].i]++;$('#allocation-text').textContent=proposal.map((v,i)=>`รายการ ${i+1}: ${money(cents(items[i].vat))} → ${money(v)} บาท`).join(' / ');$('#allocation').hidden=false;$('#message').textContent='';};
$('#apply').onclick=()=>{if(proposal){items.forEach((r,i)=>r.vat=(proposal[i]/100).toFixed(2));invalidate();render()}};$('#cancel').onclick=()=>{proposal=null;$('#allocation').hidden=true;totals()};
$('#preview').onclick=async()=>{if(photoBusy){$('#message').textContent='กรุณารอเตรียมรูปภาพให้เสร็จ';return;}if(!form.reportValidity())return;const current=version;busy=true;totals();$('#message').textContent='กำลังจัดหน้าเอกสาร…';try{const data=Object.fromEntries(new FormData(form));data.images=photos.map(p=>p.data);data.items=items;data.budgets=budgets;const issue=budgetIssue();if(issue)throw Error(issue);const r=await fetch('/api/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error((await r.json()).error);const result=await r.json();const blob=new Blob([Uint8Array.from(atob(result.pdf),c=>c.charCodeAt(0))],{type:"application/pdf"});if(current!==version){$('#message').textContent='มีการแก้ข้อมูลระหว่างสร้าง กรุณาสร้างตัวอย่างใหม่';return}url=URL.createObjectURL(blob);$('#pdf').replaceChildren(...result.pages.map((p,i)=>{const image=document.createElement('img');image.src='data:image/png;base64,'+p;image.alt='เอกสารหน้า '+(i+1);image.style.width='100%';return image}));$('#pdf').hidden=false;$('#empty').hidden=true;$('#download').href=url;$('#download').hidden=false;$('#document-print').hidden=false;$('#preview-status').textContent='ข้อมูลล่าสุด';$('#message').textContent='สร้าง PDF แล้ว พร้อมดาวน์โหลด';document.querySelector('.preview-card').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){$('#message').textContent=e.message}finally{busy=false;totals()}};



function setMembers(){const n=Number($('#member-count').value);for(let i=1;i<=2;i++){const input=form.elements['member'+i];$('#member'+i+'-field').hidden=i>n;input.disabled=i>n;input.required=i<=n;}invalidate();}
$('#member-count').onchange=setMembers;
const budgetKeys={costCenter:'ศูนย์ต้นทุน',budgetFile:'แฟ้มงาน',network:'โครงข่าย',expense:'ประเภทค่า',account:'รหัสบัญชีและชื่อบัญชี'};
function budgetIssue(){const used=items.map(()=>0);for(const b of budgets){if(!b.itemIndices.length)return 'กรุณาเลือกสินค้าให้ทุกรายการงบ';for(const i of b.itemIndices)used[i]++;}if(used.some(n=>n>1))return 'สินค้าบางรายการถูกเลือกซ้ำในหลายงบ';if(used.some(n=>n===0))return 'กรุณาเลือกงบให้สินค้าทุกรายการ';return '';}
function updateBudgetStatus(){const issue=budgetIssue();$('#budget-status').textContent=issue||'จัดสรรงบครบทุกสินค้าแล้ว';$('#budget-status').style.color=issue?'#a23b4b':'#43805d';document.querySelectorAll('.budget-amount').forEach((el,i)=>el.textContent='รวม VAT '+money((budgets[i]?.itemIndices||[]).reduce((a,j)=>a+base(items[j])+cents(items[j].vat),0))+' บาท');}
function updateBudgetChoices(){document.querySelectorAll('.item-choice input').forEach(check=>{const index=Number(check.dataset.budgetIndex),item=Number(check.dataset.itemIndex),owner=budgets.findIndex((b,i)=>i!==index&&b.itemIndices.includes(item));check.disabled=owner!==-1;const label=check.closest('.item-choice');label.classList.toggle('is-unavailable',check.disabled);label.title=check.disabled?'เลือกไว้ในรายการงบ '+(owner+1)+' แล้ว กรุณายกเลิกจากงบนั้นก่อน':'';});}
function renderBudgets(){const host=$('#budgets');host.replaceChildren();budgets.forEach((b,index)=>{const card=document.createElement('fieldset');card.className='budget-line';const legend=document.createElement('legend');legend.textContent='รายการงบ '+(index+1);card.append(legend);const top=document.createElement('div');top.className='section-head';const label=document.createElement('label');label.textContent='ประเภทเงิน';const type=document.createElement('select');for(const v of ['งบทำการ','งบแฟ้มงาน']){const o=document.createElement('option');o.value=v;o.textContent=v;type.append(o)}type.value=b.type;type.onchange=()=>{b.type=type.value;invalidate();renderBudgets()};label.append(type);top.append(label);const remove=document.createElement('button');remove.type='button';remove.className='quiet';remove.textContent='ลบรายการงบ';remove.disabled=budgets.length===1;remove.onclick=()=>{budgets.splice(index,1);invalidate();renderBudgets()};top.append(remove);card.append(top);const grid=document.createElement('div');grid.className='grid';for(const [k,title]of Object.entries(budgetKeys)){if(b.type==='งบทำการ'&&['budgetFile','network','expense'].includes(k))continue;const l=document.createElement('label');l.textContent=title;const input=document.createElement('input');input.dataset.options=k+'-options';input.setAttribute('aria-label',title+' งบ '+(index+1));input.value=b[k]||'';input.maxLength=200;input.required=true;input.placeholder='เลือกหรือพิมพ์เอง';input.oninput=()=>{linkBudget(b,k,input.value);for(const key of ['budgetFile','network','expense']){const linked=card.querySelector('[data-options='+key+'-options]');if(linked&&linked!==input)linked.value=b[key]||'';}invalidate()};l.append(input);attachPicker(input);grid.append(l)}card.append(grid);const title=document.createElement('p');title.textContent='สินค้าใช้จ่ายจากงบนี้';card.append(title);items.forEach((r,j)=>{const l=document.createElement('label');l.className='item-choice';const check=document.createElement('input');check.type='checkbox';check.dataset.budgetIndex=index;check.dataset.itemIndex=j;check.checked=b.itemIndices.includes(j);check.onchange=()=>{b.itemIndices=check.checked?[...b.itemIndices,j]:b.itemIndices.filter(i=>i!==j);invalidate();updateBudgetChoices();updateBudgetStatus()};l.append(check,document.createTextNode((j+1)+'. '+(r.name||'ยังไม่ระบุชื่อ')));card.append(l)});const amount=document.createElement('p');amount.className='budget-amount';card.append(amount);host.append(card)});$('#add-budget').disabled=budgets.length>=items.length;updateBudgetChoices();updateBudgetStatus();}
$('#add-budget').onclick=()=>{budgets.push({type:'งบแฟ้มงาน',costCenter:'',budgetFile:'',network:'',expense:'',account:'',itemIndices:[]});invalidate();renderBudgets()};
form.addEventListener('input',e=>{if(e.target.closest('#rows')){if(e.target.type==='text')renderBudgets();else updateBudgetStatus();}});
function renderPhotos(){const host=$('#photo-list');host.replaceChildren();photos.forEach((p,i)=>{const card=document.createElement('div'),img=document.createElement('img'),name=document.createElement('p'),remove=document.createElement('button');img.src=p.data;img.alt='รูปที่ '+(i+1);name.textContent=p.name;remove.type='button';remove.textContent='ลบรูปที่ '+(i+1);remove.disabled=photoBusy;remove.onclick=()=>{photos.splice(i,1);invalidate();renderPhotos()};card.append(img,name,remove);host.append(card)});$('#photos').disabled=photoBusy||photos.length===3;$('#photo-status').textContent=photoBusy?'กำลังเตรียมรูปภาพ…':photos.length+' / 3 รูป';}
async function preparePhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('กรุณาเลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 10 MB');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const scale=Math.min(1,1200/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return {name:file.name,data:canvas.toDataURL('image/jpeg',.85)};}finally{URL.revokeObjectURL(url)}}
$('#photos').onchange=async()=>{const files=Array.from($('#photos').files);$('#photos').value='';if(photos.length+files.length>3){$('#photo-status').textContent='เลือกได้สูงสุด 3 รูป กรุณาเลือกใหม่';return;}const generation=photoGeneration;photoBusy=true;invalidate();renderPhotos();try{const added=[];for(const file of files)added.push(await preparePhoto(file));if(generation===photoGeneration)photos.push(...added);}catch(e){$('#message').textContent=e.message;}finally{photoBusy=false;renderPhotos();scheduleDraft();}};

function scheduleDraft(){if(!draftReady)return;draftDirty=true;$('#draft-status').textContent='มีการแก้ไข · กำลังบันทึก…';clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,400);}
async function saveDraft(){if(!draftReady||draftSaving||photoBusy||!draftDirty)return;draftSaving=true;draftDirty=false;const snapshot={schema:1,fields:Object.fromEntries(new FormData(form)),items,budgets,photos,memberCount:$('#member-count').value,savedAt:new Date().toISOString()};try{const r=await fetch('/api/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot)});if(!r.ok)throw Error();if(!draftDirty)$('#draft-status').textContent='บันทึกร่างบนเครื่องแล้ว · '+new Date().toLocaleTimeString('th-TH');}catch(e){draftDirty=true;$('#draft-status').textContent='บันทึกไม่สำเร็จ กรุณาเปิดโปรแกรมไว้แล้วลองแก้ไขอีกครั้ง';}finally{draftSaving=false;if(draftDirty)draftTimer=setTimeout(saveDraft,2500);}}
async function openDraft(){form.inert=true;$('#preview').disabled=true;reset();try{await loadMaster();const r=await fetch('/api/draft');if(!r.ok)throw Error();const d=await r.json();if(d){for(const [k,v]of Object.entries(d.fields))if(form.elements[k])form.elements[k].value=v;items=d.items;budgets=d.budgets;photos=d.photos;$('#member-count').value=d.memberCount;setMembers();renderPhotos();renderBudgets();render();$('#draft-status').textContent='เปิดร่างล่าสุดที่บันทึกไว้แล้ว';}else $('#draft-status').textContent='พร้อมทดลอง · แก้ข้อมูลแล้วจะบันทึกอัตโนมัติ';draftReady=true;$('#reset').disabled=false;}catch(e){$('#draft-status').textContent='เปิดร่างไม่สำเร็จ กรุณาโหลดหน้าใหม่ก่อนเริ่มกรอก';}finally{form.inert=!draftReady;totals();$('#preview').disabled=!draftReady;}}
window.addEventListener('beforeunload',e=>{if(draftDirty||draftSaving||photoBusy){e.preventDefault();e.returnValue='';}});

let master={budgetFiles:[],people:[]};
function linkBudget(b,key,value){b[key]=value;if(!['budgetFile','network'].includes(key))return;const entry=master.budgetFiles.find(f=>key==='budgetFile'?f.code===value:f.networks.some(n=>n.code===value));if(entry){b.budgetFile=entry.code;if(key==='budgetFile'&&!entry.networks.some(n=>n.code===b.network))b.network=entry.networks.length===1?entry.networks[0].code:'';const network=entry.networks.find(n=>n.code===b.network);if(!(network?.expenses||entry.expenses).includes(b.expense))b.expense='';}else if(key==='budgetFile'){b.network='';}else{b.budgetFile='';}}
function optionsFor(input){const id=input.dataset.options;if(['person-options','approver-options'].includes(id))return master.people.map(p=>({value:p.name,label:p.name+' — '+p.position,position:p.position}));let list=Array.from(document.getElementById(id)?.options||[]).map(o=>({value:o.value,label:o.label||o.value}));const field=input.closest('fieldset'),file=field?.querySelector('[data-options=budgetFile-options]')?.value,entry=master.budgetFiles.find(f=>f.code===file);if(id==='network-options'&&file)list=(entry?.networks||[]).map(n=>({value:n.code,label:n.code+' — '+n.name}));if(id==='expense-options'&&entry){const selected=field?.querySelector('[data-options=network-options]')?.value,network=entry.networks.find(n=>n.code===selected);list=(network?.expenses||entry.expenses).map(v=>({value:v,label:v}));}return list;}
function attachPicker(input){if(input.dataset.picker)return;input.dataset.picker='1';if(['person-options','approver-options'].includes(input.dataset.options)){const h=document.createElement('input');h.type='hidden';h.name=input.name+'Position';input.form.append(h);input.addEventListener('input',()=>{h.value='';});}const wrap=document.createElement('div');wrap.className='picker';input.parentNode.insertBefore(wrap,input);wrap.append(input);const toggle=document.createElement('button');toggle.type='button';toggle.className='picker-toggle';toggle.textContent='▾';toggle.setAttribute('aria-label','เปิดตัวเลือกทั้งหมด '+(input.getAttribute('aria-label')||input.name));toggle.setAttribute('aria-expanded','false');const list=document.createElement('div');list.className='picker-list';list.hidden=true;list.setAttribute('role','listbox');wrap.append(toggle,list);const show=(query='')=>{list.replaceChildren();const opts=optionsFor(input).filter(o=>(o.value+' '+o.label).toLowerCase().includes(query.toLowerCase()));for(const o of opts){const b=document.createElement('button');b.type='button';b.setAttribute('role','option');b.textContent=o.label;b.onclick=()=>{input.value=o.value;input.dispatchEvent(new Event('input',{bubbles:true}));if(o.position!==undefined){input.form.elements[input.name+'Position'].value=o.position;}list.hidden=true;toggle.setAttribute('aria-expanded','false');input.focus()};list.append(b)}if(!opts.length){const hint=document.createElement('p');hint.textContent='ไม่พบข้อมูลในรายการ สามารถพิมพ์เองได้';list.append(hint)}list.hidden=false;toggle.setAttribute('aria-expanded','true')};toggle.onclick=()=>{if(list.hidden)show();else{list.hidden=true;toggle.setAttribute('aria-expanded','false')}};input.addEventListener('input',()=>show(input.value));input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();show();list.querySelector('button')?.focus()}if(e.key==='Escape'){list.hidden=true;toggle.setAttribute('aria-expanded','false')}});wrap.addEventListener('focusout',()=>setTimeout(()=>{if(!wrap.contains(document.activeElement)){list.hidden=true;toggle.setAttribute('aria-expanded','false')}},0));}
async function loadMaster(){const r=await fetch('/master-data.json');if(!r.ok)throw Error('เปิดข้อมูล Excel ไม่สำเร็จ');master=await r.json();const fill=(id,rows)=>{const list=document.getElementById(id);list.replaceChildren(...rows.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.label=label;return o}))};fill('costCenter-options',master.costCenters.map(x=>[x.code,x.name]));fill('account-options',master.accounts.map(x=>[x.code+' ('+x.name+')',x.code+' — '+x.name]));fill('budgetFile-options',master.budgetFiles.map(x=>[x.code,x.code+' — '+x.name+' ['+x.sheet+']']));fill('network-options',master.budgetFiles.flatMap(x=>x.networks.map(n=>[n.code,n.code+' — '+x.code+' — '+n.name])));fill('expense-options',[...new Set(master.budgetFiles.flatMap(x=>x.expenses))].map(x=>[x,x]));for(const id of ['person-options','approver-options'])fill(id,master.people.map(x=>[x.name,x.name+' — '+x.position]));document.querySelectorAll('input[list]').forEach(input=>{input.dataset.options=input.getAttribute('list');input.removeAttribute('list');attachPicker(input)});$('#master-status').textContent='ข้อมูลจาก Excel: ศูนย์ต้นทุน '+master.costCenters.length+' แห่ง · แฟ้มงาน '+master.budgetFiles.length+' แฟ้ม · รหัสบัญชี '+master.accounts.length+' รายการ · บุคลากร '+master.people.length+' คน';}
const hiringScript=document.createElement('script');hiringScript.src='/hiring-ui.js';hiringScript.onload=()=>openDraft().then(updateDocumentType);hiringScript.onerror=()=>{$('#draft-status').textContent='โหลดโมดูลเอกสารไม่สำเร็จ กรุณาโหลดหน้าใหม่';};document.body.append(hiringScript);

window.applyBudgetMaster=async data=>{await loadMaster();renderBudgets();invalidate();};
document.addEventListener("budget-sync-locked",invalidate);

$('#document-print').onclick=async()=>{const current=url;if(!current)return;try{await Promise.all(Array.from(document.querySelectorAll('#pdf img'),img=>img.decode()));if(url===current)window.print();}catch(e){$('#message').textContent='ตัวอย่างยังไม่พร้อม กรุณาสร้างตัวอย่างใหม่';}};
