(()=>{
const $=s=>document.querySelector(s),form=$('#budget-form'),host=$('#budget-rows');
let accounts=[],people=[],photos=[],photoBusy=false,rows=[],url=null,busy=false,version=0,ready=false;
const amounts=[['approved','งบประมาณอนุมัติ'],['paid','จ่ายไปแล้ว'],['balanceBefore','คงเหลือก่อนจ่ายครั้งนี้'],['payment','จ่ายครั้งนี้'],['balanceAfter','คงเหลือหลังจ่ายครั้งนี้']];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function invalidate(){version++;if(url)URL.revokeObjectURL(url);url=null;$('#budget-download').hidden=true;$('#budget-print').hidden=true;$('#budget-preview').replaceChildren();$('#budget-empty').hidden=false;$('#budget-status').textContent='ข้อมูลเปลี่ยนแล้ว กรุณาสร้างตัวอย่างใหม่';}
function add(){rows.push({description:'',date:today(),department:'',accountCode:'',orderNumber:'',controller:'',approved:'',paid:'',balanceBefore:'',payment:'',balanceAfter:''});invalidate();render();}
function render(){host.replaceChildren();rows.forEach((row,index)=>{
 const card=document.createElement('section');card.className='card budget-row';
 const head=document.createElement('div');head.className='section-head';const h=document.createElement('h2');h.textContent='รายการที่ '+(index+1);const remove=document.createElement('button');remove.type='button';remove.textContent='ลบรายการ';remove.disabled=rows.length===1;remove.onclick=()=>{rows.splice(index,1);invalidate();render();};head.append(h,remove);card.append(head);
 const grid=document.createElement('div');grid.className='grid';card.append(grid);
 function field(key,label,type='text',options=null){const l=document.createElement('label');l.className=options?'budget-choice':type==='date'?'budget-date':'budget-manual';l.textContent=label;const input=document.createElement(options?'select':'input');input.name=key+'-'+index;input.required=key!=='orderNumber';if(key.startsWith('balance')){input.readOnly=true;l.className='budget-calculated';}
 if(options){const empty=document.createElement('option');empty.value='';empty.textContent='เลือก'+label;input.append(empty);for(const [value,text]of options){const o=document.createElement('option');o.value=value;o.textContent=text;input.append(o);}}
 else{input.type=type;if(type==='number'){input.step='.01';if(!key.startsWith('balance'))input.min='0';}if(type==='text')input.maxLength=key==='description'?100:30;}
 input.value=row[key]??'';input.oninput=()=>{row[key]=input.value;if(['approved','paid','payment'].includes(key)){const cents=v=>Math.round(Number(v)*100);row.balanceBefore=row.approved!==''&&row.paid!==''?((cents(row.approved)-cents(row.paid))/100).toFixed(2):'';row.balanceAfter=row.balanceBefore!==''&&row.payment!==''?((cents(row.approved)-cents(row.paid)-cents(row.payment))/100).toFixed(2):'';for(const k of ['balanceBefore','balanceAfter'])grid.querySelector('[name='+k+'-'+index+']').value=row[k];}invalidate();};l.append(input);grid.append(l);return input;}
 field('description','รายละเอียดรายการ').parentElement.classList.add('budget-wide');
 field('date','วันที่','date');field('department','แผนก','text',['ผปร.','ผบค.','ผบง.','ผกป.','กบห.'].map(d=>[d,d]));field('orderNumber','หมายเลขใบสั่ง (ถ้ามี)');
 const code=field('accountCode','รหัสบัญชี','text',accounts.map(a=>[a.code,a.code+' — '+a.name]));
 const name=field('accountCode','บัญชี','text',accounts.map(a=>[a.code,a.name+' — '+a.code]));name.name='accountName-'+index;
 const link=input=>{row.accountCode=input.value;code.value=name.value=input.value;invalidate();};code.oninput=()=>link(code);name.oninput=()=>link(name);
 field('controller','ผู้ควบคุมงบ','text',people.map(p=>[JSON.stringify({name:p.name,position:p.position}),p.name+' — '+p.position]));
 for(const [key,label]of amounts)field(key,label+' (บาท)','number');
 const note=document.createElement('p');note.className='hint';note.textContent='ยอดคงเหลือคำนวณอัตโนมัติทันทีจากงบประมาณอนุมัติ − จ่ายไปแล้ว − จ่ายครั้งนี้';card.append(note);host.append(card);
 });$('#budget-add').disabled=busy;}
form.onsubmit=async e=>{e.preventDefault();if(busy||photoBusy||!ready||!form.reportValidity())return;invalidate();const requestedVersion=version;busy=true;$('#budget-create').disabled=true;$('#budget-add').disabled=true;$('#budget-status').textContent='กำลังสร้างตัวอย่าง PDF…';try{const r=await fetch('/api/budget/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,images:photos.map(p=>p.data)})});const result=await r.json();if(!r.ok)throw Error(result.error);if(version!==requestedVersion){$('#budget-status').textContent='ข้อมูลเปลี่ยนระหว่างสร้าง กรุณาสร้างตัวอย่างใหม่';return;}url=URL.createObjectURL(new Blob([Uint8Array.from(atob(result.pdf),c=>c.charCodeAt(0))],{type:'application/pdf'}));$('#budget-preview').replaceChildren(...result.pages.map((p,i)=>{const img=document.createElement('img');img.src='data:image/png;base64,'+p;img.alt='ตัวอย่างใบตัดงบทำการ หน้า '+(i+1);return img;}));$('#budget-empty').hidden=true;$('#budget-download').href=url;$('#budget-download').hidden=false;$('#budget-print').hidden=false;$('#budget-status').textContent='สร้างตัวอย่างแล้ว ตรวจเอกสารก่อนดาวน์โหลด';$('#budget-preview').scrollIntoView({behavior:'smooth'});}catch(error){$('#budget-status').textContent=error.message;}finally{busy=false;$('#budget-create').disabled=!ready;$('#budget-add').disabled=false;}};
function renderPhotos(){const host=$('#budget-photos');host.replaceChildren();photos.forEach((p,i)=>{const figure=document.createElement('figure'),image=document.createElement('img'),remove=document.createElement('button');image.src=p.data;image.alt=p.name;remove.type='button';remove.textContent='ลบรูปที่ '+(i+1);remove.disabled=photoBusy;remove.onclick=()=>{photos.splice(i,1);invalidate();renderPhotos();};figure.append(image,remove);host.append(figure);});$('#budget-photo-input').disabled=photoBusy||photos.length>=3;}
async function preparePhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('กรุณาใช้ JPG, PNG หรือ WebP ขนาดไม่เกิน 15 MB ต่อรูป');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext('2d');context.fillStyle='white';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.85);if(data.length>3000000)throw Error('รูปมีขนาดใหญ่เกินไป กรุณาลดขนาดรูป');return {name:file.name,data};}finally{bitmap.close();}}
$('#budget-photo-input').onchange=async e=>{const files=Array.from(e.target.files);e.target.value='';if(files.length+photos.length>3){$('#budget-photo-status').textContent='แนบได้สูงสุด 3 รูป กรุณาเลือกใหม่';return;}photoBusy=true;invalidate();renderPhotos();$('#budget-photo-status').textContent='กำลังเตรียมรูป…';try{const added=[];for(const file of files)added.push(await preparePhoto(file));photos.push(...added);invalidate();$('#budget-photo-status').textContent='แนบแล้ว '+photos.length+' / 3 รูป';}catch(error){$('#budget-photo-status').textContent=error.message;}finally{photoBusy=false;renderPhotos();}};
$('#budget-print').onclick=async()=>{if(!url)return;try{await Promise.all(Array.from(document.querySelectorAll('#budget-preview img'),img=>img.decode()));if(url)window.print();}catch(e){$('#budget-status').textContent='รูปตัวอย่างยังไม่พร้อม กรุณาสร้างตัวอย่างใหม่';}};
$('#budget-add').onclick=add;window.addEventListener('scroll',()=>{$('#budget-top').hidden=window.scrollY<300;},{passive:true});$('#budget-top').onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
fetch('/master-data.json').then(r=>{if(!r.ok)throw Error('โหลดข้อมูลบัญชีไม่ได้');return r.json();}).then(data=>{accounts=data.accounts;people=data.people;ready=true;add();$('#budget-create').disabled=false;$('#budget-status').textContent='พร้อมกรอกข้อมูล';}).catch(e=>{$('#budget-status').textContent=e.message;$('#budget-add').disabled=true;});
})();