from pathlib import Path
p=Path('prototype/index.html');s=p.read_text(encoding='utf-8-sig')
start=s.index('<section class="card"><h2><span>03')
end=s.index('</form>',start)
s=s[:start]+'''<section class="card"><div class="section-head"><h2><span>03</span> ข้อมูลงบประมาณ</h2><button type="button" id="add-budget">+ เพิ่มรายการงบ</button></div><p class="hint">เลือกจากรายการหรือพิมพ์เองได้ · เลือกสินค้าที่ใช้แต่ละงบให้ครบและไม่ซ้ำกัน</p><div id="budgets"></div><p id="budget-status" role="status"></p><p class="hint">ตัวเลือกตั้งต้นจากข้อมูลที่เคยระบุ ยังไม่เชื่อมไฟล์ Excel ล่าสุด</p></section>
<section class="card"><h2><span>04</span> บุคลากรในเอกสาร</h2><p class="hint">เลือกชื่อหรือพิมพ์เองได้ · ประธาน 1 คน และกรรมการเพิ่มเติม 0–2 คน</p><div class="grid"><label>ประธานกรรมการ<input name="chair" list="person-options" maxlength="40" required></label><label>จำนวนกรรมการเพิ่มเติม<select id="member-count"><option value="0">ไม่มีกรรมการเพิ่มเติม</option><option value="1">1 คน</option><option value="2">2 คน</option></select></label><label id="member1-field">กรรมการคนที่ 1<input name="member1" list="person-options" maxlength="40"></label><label id="member2-field">กรรมการคนที่ 2<input name="member2" list="person-options" maxlength="40"></label><label>เจ้าหน้าที่จัดทำ<input name="officer" list="person-options" maxlength="40" required></label><label>ผู้อนุมัติ<input name="approver" list="approver-options" maxlength="40" required></label><label>ผู้รับของ<input name="receiver" list="person-options" maxlength="40" required></label></div><p class="hint">รายชื่อเป็นตัวเลือกตั้งต้น ตำแหน่งยังใช้ข้อความตัวอย่างใน PDF</p></section>
<datalist id="person-options"><option value="ประธานตัวอย่าง"><option value="กรรมการตัวอย่างหนึ่ง"><option value="กรรมการตัวอย่างสอง"><option value="เจ้าหน้าที่ตัวอย่าง"><option value="ผู้รับของตัวอย่าง"></datalist>
<datalist id="approver-options"><option value="นายอาคม อุดมสารี"><option value="นายจิรยุทธ์ ฟูเถิ้ม"><option value="นายธีรภัทร ทิพย์สุภา"><option value="ผู้อนุมัติตัวอย่าง"></datalist>
<datalist id="costCenter-options"><option value="A311201010" label="ผปร."><option value="A311201020" label="ผบค."><option value="A311201000" label="กบห."><option value="A311201030" label="ผบง."></datalist>
<datalist id="budgetFile-options"><option value="I-69-A-PHOPS.JL.0005"></datalist><datalist id="network-options"><option value="7001169470"></datalist><datalist id="expense-options"><option value="ค่าเบ็ดเตล็ด (0060)"><option value="ค่าแรง (0030)"><option value="ค่าควบคุมงาน (0040)"><option value="ค่าขนส่ง (0050)"></datalist><datalist id="account-options"><option value="53051090 (ค่าวัสดุเบ็ดเตล็ดด้านช่าง)"></datalist>
'''+s[end:]
s=s.replace('ตัวอย่าง 4 หน้าจะปรากฏที่นี่','ตัวอย่างเอกสารจะปรากฏที่นี่')
s=s.replace('<script src="/app.js"></script>','<script src="/app.js"></script>')
p.write_text(s,encoding='utf-8')
p=Path('prototype/app.js');s=p.read_text(encoding='utf-8-sig')
s=s.replace('let items=[],proposal=', 'let budgets=[],items=[],proposal=')
s=s.replace('form.elements[k].value=v','form.elements[k]&&(form.elements[k].value=v)')
s=s.replace("invalidate();render();$('#message').textContent='';}","budgets=[{type:'งบแฟ้มงาน',costCenter:initial.costCenter,budgetFile:initial.budgetFile,network:initial.network,expense:initial.expense,account:initial.account,itemIndices:[0,1,2]}];$('#member-count').value='2';setMembers();invalidate();render();renderBudgets();$('#message').textContent='';}")
s=s.replace('items.splice(i,1);invalidate();render()',"items.splice(i,1);budgets.forEach(b=>b.itemIndices=b.itemIndices.filter(j=>j!==i).map(j=>j>i?j-1:j));invalidate();render();renderBudgets()")
s=s.replace("manual:false});invalidate();render()","manual:false});invalidate();render();renderBudgets()")
s=s.replace('data.items=items;','data.items=items;data.budgets=budgets;const issue=budgetIssue();if(issue)throw Error(issue);')
s=s.replace("$('#pdf').src=url;","$('#pdf').replaceChildren(...result.pages.map((p,i)=>{const image=document.createElement('img');image.src='data:image/png;base64,'+p;image.alt='เอกสารหน้า '+(i+1);image.style.width='100%';return image}));")
s=s.replace('};reset();','};\n')
s+='''
function setMembers(){const n=Number($('#member-count').value);for(let i=1;i<=2;i++){const input=form.elements['member'+i];$('#member'+i+'-field').hidden=i>n;input.disabled=i>n;input.required=i<=n;}invalidate();}
$('#member-count').onchange=setMembers;
const budgetKeys={costCenter:'ศูนย์ต้นทุน',budgetFile:'แฟ้มงาน',network:'โครงข่าย',expense:'ประเภทค่า',account:'รหัสบัญชีและชื่อบัญชี'};
function budgetIssue(){const used=items.map(()=>0);for(const b of budgets){if(!b.itemIndices.length)return 'กรุณาเลือกสินค้าให้ทุกรายการงบ';for(const i of b.itemIndices)used[i]++;}if(used.some(n=>n>1))return 'สินค้าบางรายการถูกเลือกซ้ำในหลายงบ';if(used.some(n=>n===0))return 'กรุณาเลือกงบให้สินค้าทุกรายการ';return '';}
function updateBudgetStatus(){const issue=budgetIssue();$('#budget-status').textContent=issue||'จัดสรรงบครบทุกสินค้าแล้ว';$('#budget-status').style.color=issue?'#a23b4b':'#43805d';document.querySelectorAll('.budget-amount').forEach((el,i)=>el.textContent='รวม VAT '+money(budgets[i].itemIndices.reduce((a,j)=>a+base(items[j])+cents(items[j].vat),0))+' บาท');}
function renderBudgets(){const host=$('#budgets');host.replaceChildren();budgets.forEach((b,index)=>{const card=document.createElement('fieldset');card.className='budget-line';const legend=document.createElement('legend');legend.textContent='รายการงบ '+(index+1);card.append(legend);const top=document.createElement('div');top.className='section-head';const label=document.createElement('label');label.textContent='ประเภทเงิน';const type=document.createElement('select');for(const v of ['งบทำการ','งบแฟ้มงาน']){const o=document.createElement('option');o.value=v;o.textContent=v;type.append(o)}type.value=b.type;type.onchange=()=>{b.type=type.value;invalidate();renderBudgets()};label.append(type);top.append(label);const remove=document.createElement('button');remove.type='button';remove.className='quiet';remove.textContent='ลบรายการงบ';remove.disabled=budgets.length===1;remove.onclick=()=>{budgets.splice(index,1);invalidate();renderBudgets()};top.append(remove);card.append(top);const grid=document.createElement('div');grid.className='grid';for(const [k,title]of Object.entries(budgetKeys)){if(b.type==='งบทำการ'&&['budgetFile','network'].includes(k))continue;const l=document.createElement('label');l.textContent=title;const input=document.createElement('input');input.setAttribute('list',k+'-options');input.setAttribute('aria-label',title+' งบ '+(index+1));input.value=b[k]||'';input.maxLength=80;input.required=true;input.placeholder='เลือกหรือพิมพ์เอง';input.oninput=()=>{b[k]=input.value;invalidate()};l.append(input);grid.append(l)}card.append(grid);const title=document.createElement('p');title.textContent='สินค้าใช้จ่ายจากงบนี้';card.append(title);items.forEach((r,j)=>{const l=document.createElement('label');l.className='item-choice';const check=document.createElement('input');check.type='checkbox';check.checked=b.itemIndices.includes(j);check.onchange=()=>{b.itemIndices=check.checked?[...b.itemIndices,j]:b.itemIndices.filter(i=>i!==j);invalidate();updateBudgetStatus()};l.append(check,document.createTextNode((j+1)+'. '+(r.name||'ยังไม่ระบุชื่อ')));card.append(l)});const amount=document.createElement('p');amount.className='budget-amount';card.append(amount);host.append(card)});$('#add-budget').disabled=budgets.length>=items.length;updateBudgetStatus();}
$('#add-budget').onclick=()=>{budgets.push({type:'งบแฟ้มงาน',costCenter:'',budgetFile:'',network:'',expense:'',account:'',itemIndices:[]});invalidate();renderBudgets()};
form.addEventListener('input',e=>{if(e.target.closest('#rows')){if(e.target.type==='text')renderBudgets();else updateBudgetStatus();}});
reset();
'''
p.write_text(s,encoding='utf-8')
