from pathlib import Path
p=Path('prototype/server.py');s=p.read_text(encoding='utf-8').replace("if not 1<=len(rows)<=3:raise ValueError('รุ่นทดลองรองรับ 1–3 รายการ')","if not isinstance(rows,list) or not rows:raise ValueError('กรุณาเพิ่มรายการพัสดุ')").replace("not 1<=len(d['items'])<=3","not len(d['items'])>=1").replace("not 1<=len(d['budgets'])<=3","not len(d['budgets'])>=1").replace("files={'/':", "files={'/master-data.json':ROOT/'master-data.json','/':").replace("mime={'/':", "mime={'/master-data.json':'application/json; charset=utf-8','/':").replace('timeout=45','timeout=180').replace('timeout=30','timeout=180').replace("sorted(temp.glob('page-*.png'))","sorted(temp.glob('page-*.png'),key=lambda p:int(p.stem.split('-')[-1]))")
s=s.replace("len(str(b[k]))>80","len(str(b[k]))>200")
p.write_text(s,encoding='utf-8')
p=Path('prototype/app.js');s=p.read_text(encoding='utf-8').replace("$('#add').disabled=items.length>=3;","$('#add').disabled=false;").replace('if(items.length<3){','if(true){').replace('input.maxLength=80','input.maxLength=200')
s=s.replace("input.setAttribute('list',k+'-options');", "input.dataset.options=k+'-options';")
s=s.replace("l.append(input);grid.append(l)","l.append(input);attachPicker(input);grid.append(l)")
s=s.replace("b[k]=input.value;invalidate()", "b[k]=input.value;if(k==='budgetFile'){const entry=master.budgetFiles.find(f=>f.code===input.value);if(entry){b.network=entry.network;const network=card.querySelector('[data-options=network-options]');if(network)network.value=b.network;}}invalidate()")
s=s.replace("const r=await fetch('/api/draft');", "await loadMaster();const r=await fetch('/api/draft');")
s=s.replace('openDraft();','''
let master={budgetFiles:[],people:[]};
function optionsFor(input){const id=input.dataset.options;let list=Array.from(document.getElementById(id)?.options||[]).map(o=>({value:o.value,label:o.label||o.value}));if(id==='expense-options'){const field=input.closest('fieldset'),file=field?.querySelector('[data-options=budgetFile-options]')?.value,entry=master.budgetFiles.find(f=>f.code===file);if(entry)list=entry.expenses.map(v=>({value:v,label:v}));}return list;}
function attachPicker(input){if(input.dataset.picker)return;input.dataset.picker='1';const wrap=document.createElement('div');wrap.className='picker';input.parentNode.insertBefore(wrap,input);wrap.append(input);const toggle=document.createElement('button');toggle.type='button';toggle.className='picker-toggle';toggle.textContent='▾';toggle.setAttribute('aria-label','เปิดตัวเลือกทั้งหมด '+(input.getAttribute('aria-label')||input.name));toggle.setAttribute('aria-expanded','false');const list=document.createElement('div');list.className='picker-list';list.hidden=true;list.setAttribute('role','listbox');wrap.append(toggle,list);const show=(query='')=>{list.replaceChildren();const opts=optionsFor(input).filter(o=>(o.value+' '+o.label).toLowerCase().includes(query.toLowerCase()));for(const o of opts){const b=document.createElement('button');b.type='button';b.setAttribute('role','option');b.textContent=o.label;b.onclick=()=>{input.value=o.value;input.dispatchEvent(new Event('input',{bubbles:true}));list.hidden=true;toggle.setAttribute('aria-expanded','false');input.focus()};list.append(b)}if(!opts.length){const hint=document.createElement('p');hint.textContent='ไม่พบข้อมูลในรายการ สามารถพิมพ์เองได้';list.append(hint)}list.hidden=false;toggle.setAttribute('aria-expanded','true')};toggle.onclick=()=>{if(list.hidden)show();else{list.hidden=true;toggle.setAttribute('aria-expanded','false')}};input.addEventListener('input',()=>show(input.value));input.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();show();list.querySelector('button')?.focus()}if(e.key==='Escape'){list.hidden=true;toggle.setAttribute('aria-expanded','false')}});wrap.addEventListener('focusout',()=>setTimeout(()=>{if(!wrap.contains(document.activeElement)){list.hidden=true;toggle.setAttribute('aria-expanded','false')}},0));}
async function loadMaster(){const r=await fetch('/master-data.json');if(!r.ok)throw Error('เปิดข้อมูล Excel ไม่สำเร็จ');master=await r.json();const fill=(id,rows)=>{const list=document.getElementById(id);list.replaceChildren(...rows.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.label=label;return o}))};fill('costCenter-options',master.costCenters.map(x=>[x.code,x.name]));fill('account-options',master.accounts.map(x=>[x.code+' ('+x.name+')',x.code+' — '+x.name]));fill('budgetFile-options',master.budgetFiles.map(x=>[x.code,x.code+' — '+x.name+' ['+x.sheet+']']));fill('network-options',master.budgetFiles.map(x=>[x.network,x.network+' — '+x.code]));fill('expense-options',[...new Set(master.budgetFiles.flatMap(x=>x.expenses))].map(x=>[x,x]));for(const id of ['person-options','approver-options'])fill(id,master.people.map(x=>[x.name,x.name+' — '+x.position]));document.querySelectorAll('input[list]').forEach(input=>{input.dataset.options=input.getAttribute('list');input.removeAttribute('list');attachPicker(input)});$('#master-status').textContent='ข้อมูลจาก Excel: ศูนย์ต้นทุน '+master.costCenters.length+' แห่ง · แฟ้มงาน '+master.budgetFiles.length+' แฟ้ม · รหัสบัญชี '+master.accounts.length+' รายการ · บุคลากร '+master.people.length+' คน';}
openDraft();''')
p.write_text(s,encoding='utf-8')
p=Path('prototype/index.html');s=p.read_text(encoding='utf-8').replace('ราคาไม่รวม VAT · รุ่นทดลองนี้รองรับไม่เกิน 3 รายการ','ราคาไม่รวม VAT · เพิ่มรายการได้ตามต้องการ PDF จะต่อหน้าอัตโนมัติ').replace('ตัวเลือกตั้งต้นจากข้อมูลที่เคยระบุ ยังไม่เชื่อมไฟล์ Excel ล่าสุด','กด ▾ เพื่อดูตัวเลือกทั้งหมด หรือพิมพ์ค้นหาและกรอกเองได้').replace('รายชื่อเป็นตัวเลือกตั้งต้น ตำแหน่งยังใช้ข้อความตัวอย่างใน PDF','รายชื่อจาก Excel · สามารถเลือกใหม่หรือพิมพ์เองได้').replace('รายชื่อเริ่มต้นยังเป็นตัวอย่าง กรุณาตรวจข้อมูลก่อนพิมพ์','กรุณาตรวจข้อมูลก่อนพิมพ์').replace('<p id="draft-status"','<p id="master-status" class="hint"></p><p id="draft-status"')
s=s.replace('</div><div class="preview-card">','</div></aside><section class="preview-card">').replace('</div></div></aside></main>','</div></section></main>')
p.write_text(s,encoding='utf-8')
p=Path('prototype/style.css');s=p.read_text(encoding='utf-8')+'''
.preview-card{grid-column:1/-1;width:100%;min-width:0}#pdf{max-width:1000px;margin:20px auto}#pdf img{display:block;width:100%;margin-bottom:24px;box-shadow:0 3px 14px #0002}.picker{position:relative;display:flex;align-items:center}.picker input{padding-right:42px;min-width:0}.picker-toggle{position:absolute;right:2px;top:5px;height:36px;width:36px;padding:0;border:0;background:#f0eaf6}.picker-list{position:absolute;top:100%;left:0;right:0;z-index:30;max-height:280px;overflow:auto;background:#fff;border:1px solid #b8a1ca;border-radius:6px;box-shadow:0 5px 14px #0002}.picker-list button{display:block;width:100%;text-align:left;border:0;border-radius:0;font-size:19px;white-space:normal}.picker-list button:focus{background:#ece2f4}.picker-list p{padding:10px;font-size:17px}
''';p.write_text(s,encoding='utf-8')
